/// Flutter icons PreferenceIcondart
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PreferenceIcondart
///      fonts:
///       - asset: fonts/PreferenceIcondart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PreferenceIcondart {
  PreferenceIcondart._();

  static const _kFontFam = 'PreferenceIcondart';

  static const IconData settings = const IconData(0xe800, fontFamily: _kFontFam);
}
